// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function ExportAllToDisk(arg1, arg2) {
  return window['go']['main']['App']['ExportAllToDisk'](arg1, arg2);
}

export function GenerateConfigs(arg1, arg2) {
  return window['go']['main']['App']['GenerateConfigs'](arg1, arg2);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LoadScanConfigFromFile() {
  return window['go']['main']['App']['LoadScanConfigFromFile']();
}

export function Presets() {
  return window['go']['main']['App']['Presets']();
}

export function RetestEndpoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['RetestEndpoint'](arg1, arg2, arg3);
}

export function RetestReachability(arg1, arg2, arg3) {
  return window['go']['main']['App']['RetestReachability'](arg1, arg2, arg3);
}

export function RetryLastScan() {
  return window['go']['main']['App']['RetryLastScan']();
}

export function SaveScanConfigToFile(arg1) {
  return window['go']['main']['App']['SaveScanConfigToFile'](arg1);
}

export function SaveText(arg1, arg2) {
  return window['go']['main']['App']['SaveText'](arg1, arg2);
}

export function SelectIPsFile() {
  return window['go']['main']['App']['SelectIPsFile']();
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function StartSpeedTest(arg1) {
  return window['go']['main']['App']['StartSpeedTest'](arg1);
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}
