// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function GenerateConfigs(arg1, arg2) {
  return window['go']['main']['App']['GenerateConfigs'](arg1, arg2);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function SaveText(arg1, arg2) {
  return window['go']['main']['App']['SaveText'](arg1, arg2);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}

export function ValidateTopIPs(arg1, arg2) {
  return window['go']['main']['App']['ValidateTopIPs'](arg1, arg2);
}
